### ISSUE TITLE
Polisy error upon updating to v1.0.3

### ISSUE THREAD

**Issue by ToddLorey** [bpaauwe/udi-weatherbit-poly#1]
Bob,
I saw that a new version was available on the Polisy nodeserver store and I tried to update it.  There seems to be an issue with the update in that it there's a message at the top of the GUI that says "pullRepo: undefined"

I'm running v2.2.8 of polyglot, if that makes any difference.

Here's the relevant polyglot log entries from when I tried to do the update:
```
2020-1-8 13:53:12 [polyglot] error: child.spawn: Error: spawn /bin/sh ENOENT
2020-1-8 13:53:12 [polyglot] error: NSChild: WeatherBit pullRepo: Non-zero exit code: -2
2020-1-8 13:53:12 [polyglot] error: NSResponse: Success: false - pullRepo: undefined

```

**Comment by bpaauwe** [comment]
That's an error from Polyglot, typically it means that it can't update the node server directory because there are local changes that would be overwritten.  There's nothing the node server can do about this.

You can try uninstalling it and then re-install it as new.

**Comment by ToddLorey** [comment]
Thanks.  That did it.  After deleting the node from the GUI, it still wouldn't let me uninstall it from the GUI so I had to go in and delete the WeatherBit.io directory from the Polisy.  I suspect it was related to the name change somehow.  The directory had the original ".io" at the end of the name when I deleted it.  Now, the directory is just WeatherBit.

All is well.  Thank you!
