### ISSUE TITLE
Node 13 comes through as code in email

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-weatherbit-poly#3]
This may be an ISY bug so I will report there too but I can put every node into email except node 13 using this command  ${sys.node.n016_forecast_1.GV13} 

All others come in fine with text and numbers except gv13 comes in codes.  I mapped them out from forecast data but that does not help when adding to an email that says Conditions Tomorrow 802 where it should say Scattered Clouds

500 Light Rain
501 Moderate Rain
503 light intensity shower rain
610 Mix Snow/Rain
801 few clouds
802 Scattered Clouds
803 Broken Clouds
804 Overcast Clouds

**Comment by bpaauwe** [comment]
I believe you have to reboot the ISY.  The ISY, like the admin console, only reads the information from the node server's files when it first starts.  Thus, for the ISY to do the mapping (in at least some cases) you need to reboot the ISY after installing the node server.

**Comment by macjeff** [comment]
You are right. I did not reboot the entire ISY.
