### ISSUE TITLE
NLS/EN_US.TXT Missing EN_COVERAGE-16  value

### ISSUE THREAD

**Issue by JavierRefuerzo** [bpaauwe/udi-weatherbit-poly#4]
Hi, I encounters this while parsing the NLS/EN_US doc for app development. Is there a reason that the Value 16 is not mapped?

EN_COVERAGE-15 = widespread
EN_COVERAGE-16 =

**Comment by bpaauwe** [comment]
I use the same NLS file for multiple node servers. The weatherbit node server doesn't actually use those entries.

For the node server that uses it, it's blank to cover the case where I see a value coming from the weather service that isn't one of the defined values, it defaults to the blank entry.

**Comment by JavierRefuerzo** [comment]
Thanks for the explanation, was not sure if this would cause errors with the ISY.
