### ISSUE TITLE
what is unit of measure for short/long poll?

### ISSUE THREAD

**Issue by oddboy** [bpaauwe/udi-weatherbit-poly#8]
Hi, 

I'm not sure what unit of measure the short and long poll uses.  In the README, you mention that anything less than 1 hour may not work on the free plan, but then the short poll defaults to 300 and long poll to 600.  So is that 300 minutes (5 hours)?  or is it in seconds? 

great node server for use with ISY btw!

thanks,

J

**Comment by bpaauwe** [comment]
Seconds.

The short/long poll values are polyglot configuration parameters, so all node servers have these and it's always in seconds.
